export enum StateType {
    Final = 'Final',
    Root = 'Root',
    Config = 'Config',
    ImplicitExpression = 'ImplicitExpression',
    RoundParenthesis = 'RoundParenthesis',
    CurlyBrace = 'CurlyBrace',
    SquareBracket = 'SquareBracket',
    AngleBracket = 'AngleBracket',
    QuoteBracket = 'QuoteBracket',
    ApostropheBracket = 'ApostropheBracket',
    ExplicitExpression = 'ExplicitExpression',
    Injection = 'Injection',
    SubgroupCondition = 'SubgroupCondition',
    BraceWait = 'BraceWait',
    ElseWait = 'ElseWait',
    Subgroup = 'Subgroup',
    MultilineSubgroup = 'MultilineSubgroup',
    Comment = 'Comment',
    Partial = 'Partial'
};
